// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0BjHXl593U0uMrb-Dp32HvU5EU9AOb-8',
    appId: '1:489088118779:web:7407dd606cf224eb53e55e',
    messagingSenderId: '489088118779',
    projectId: 'campus-manager-5cfda',
    authDomain: 'campus-manager-5cfda.firebaseapp.com',
    storageBucket: 'campus-manager-5cfda.firebasestorage.app',
    measurementId: 'G-PCGKBBSSSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmumEmqkIowEmFBccN3HHPz1mRc2lKSQ',
    appId: '1:489088118779:android:95219ab3c4e2397253e55e',
    messagingSenderId: '489088118779',
    projectId: 'campus-manager-5cfda',
    storageBucket: 'campus-manager-5cfda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTPYY4sG83iNuaNbQ-PfTli34nIug14k',
    appId: '1:489088118779:ios:1344766ade05651d53e55e',
    messagingSenderId: '489088118779',
    projectId: 'campus-manager-5cfda',
    storageBucket: 'campus-manager-5cfda.firebasestorage.app',
    iosBundleId: 'com.example.campusManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfTPYY4sG83iNuaNbQ-PfTli34nIug14k',
    appId: '1:489088118779:ios:1344766ade05651d53e55e',
    messagingSenderId: '489088118779',
    projectId: 'campus-manager-5cfda',
    storageBucket: 'campus-manager-5cfda.firebasestorage.app',
    iosBundleId: 'com.example.campusManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0BjHXl593U0uMrb-Dp32HvU5EU9AOb-8',
    appId: '1:489088118779:web:7005e64769259e0d53e55e',
    messagingSenderId: '489088118779',
    projectId: 'campus-manager-5cfda',
    authDomain: 'campus-manager-5cfda.firebaseapp.com',
    storageBucket: 'campus-manager-5cfda.firebasestorage.app',
    measurementId: 'G-JT4L2XFV75',
  );
}
